### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by KappasDEV** [Dropout1337/Twitch-Follow-Bot#1]
Dropout = skid proof lmaoo oaoaosfoewfowsdowofewofewofow oasafdadsvrwefqdqd
[proof.txt](https://github.com/Dropout1337/Twitch-Follow-Bot/files/6281914/proof.txt)

**Comment by KappasDEV** [comment]
also
[prooftogithubs.txt](https://www.youtube.com/watch?v=QtBDL8EiNZo)

**Comment by Dropout1337** [comment]
Nice proof, ill tell my manager that I don't skid and get u kicked out of the store.

**Comment by KappasDEV** [comment]
Excuse me! I am a Karen!
